dofile(minetest.get_modpath('magic_mod')..'/wands.lua')
dofile(minetest.get_modpath('magic_mod')..'/basic_attack.lua')
dofile(minetest.get_modpath('magic_mod')..'/huds.lua')
dofile(minetest.get_modpath('magic_mod')..'/craft.lua')
dofile(minetest.get_modpath('magic_mod')..'/config.txt')